languages = {"ada": "39",
             "bash": "38",
             "brainfuck": "44",
             "c (clang)": "26",
             "c (gcc)": "6",
             "c (vc)": "29",
             "c#": "1",
             "c++ (clang)": "27",
             "c++ (gcc)": "7",
             "c++ (vc++)": "28",
             "d": "30",
             "elixir": "41",
             "erlang": "40",
             "f#": "3",
             "fortran": "45",
             "go": "20",
             "haskell": "11",
             "java": "4",
             "javascript": "17",
             "kotlin": "43",
             "lisp": "18",
             "lua": "14",
             "mysql": "33",
             "nasm": "15",
             "node.js": "23",
             "objective-c": "10",
             "ocaml": "42",
             "octave": "25",
             "oracle": "35",
             "pascal": "9",
             "perl": "13",
             "php": "8",
             "postgresql": "34",
             "prolog": "19",
             "python": "5",
             "python 3": "24",
             "r": "31",
             "ruby": "12",
             "scala": "21",
             "scheme": "22",
             "sql server": "16",
             "swift": "37",
             "tcl": "32",
             "vb.net": "2"}

compiler_args = {
    "c++ (gcc)": "-Wall -std=c++14 -O2 -o a.out source_file.cpp",
    "c++ (clang)": "-Wall -std=c++14 -stdlib=libc++ -O2 -o a.out source_file.cpp",
    "c++ (vc++)": "source_file.cpp -o a.exe /EHsc /MD /I C:\\boost_1_60_0 /link /LIBPATH:C:\\boost_1_60_0\\stage\\lib",
    "c (gcc)": "-Wall -std=gnu99 -O2 -o a.out source_file.c",
    "c (clang)": "-Wall -std=gnu99 -O2 -o a.out source_file.c",
    "c (vc)": "source_file.c -o a.exe",
    "d": "source_file.d -ofa.out",
    "go": "-o a.out source_file.go",
    "haskell": "-o a.out source_file.hs",
    "objective-c": "-MMD -MP -DGNUSTEP -DGNUSTEP_BASE_LIBRARY=1 -DGNU_GUI_LIBRARY=1 -DGNU_RUNTIME=1 -DGNUSTEP_BASE_LIBRARY=1 -fno-strict-aliasing -fexceptions -fobjc-exceptions -D_NATIVE_OBJC_EXCEPTIONS -pthread -fPIC -Wall -DGSWARN -DGSDIAGNOSE -Wno-import -g -O2 -fgnu-runtime -fconstant-string-class=NSConstantString -I. -I /usr/include/GNUstep -I/usr/include/GNUstep -o a.out source_file.m -lobjc -lgnustep-base"
}
